### ISSUE TITLE
Isn't this just like a nerfed version of favorite media?

### ISSUE THREAD

**Issue by MahdeenSky** [TheLazySquid/DiscordImageFolder#1]

**Comment by TheLazySquid** [comment]
For now it 100% is. In the future I hope to give it more features, for example captions, that will hopefully give it its own niche.

**Comment by DeCat4** [comment]
Speaking of Favorite media using both plugins is impossible, the tab of this plugin overrides the Favorite Media one, would be nice if it wouldn't do that because i would actually want to have thsi separately for big image archives.

(also if you could implement a feature from favoritemedia to hide or change the position of the button would be nice)

**Comment by TheLazySquid** [comment]
This just got fixed, version 0.3.6 and above should be compatible with FavoriteMedia.
